# -*- coding: utf-8 -*-
"""WeatherForecasting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIz7j-Ub1vPa63rXoJUrG47iK8d2HT34
"""

import csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

df_tracks = pd.read_csv('/content/drive/MyDrive/seattle-weather.csv')
df_tracks

dataMapping={
    'drizzle':0,
    'rain':1,
    'fog':2,
    'sun':3,
    'snow':4
}
df_tracks['Weather']=df_tracks['weather'].map(dataMapping)
df_tracks=df_tracks.drop(['weather'],axis=1)
#df_tracks=df_tracks.loc[:,['date','precipitation','temp_max','temp_min','wind','Weather']]

#df_tracks=df_tracks.drop(['date'],axis=1)
df_tracks

attributes = ['precipitation', 'temp_max', 'temp_min', 'wind']
x=df_tracks[attributes].values
y=df_tracks['Weather'].values
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)
y_train

Model=LogisticRegression(max_iter=470)
Model.fit(X_train, y_train)
y_pred = Model.predict(X_test)
y_pred=np.array(y_pred)

DataMapping={
    0:'drizzle',
    1:'rain',
   2:'fog',
    3:'sun',
    4:'snow'
}

new=[DataMapping[value]for value in y_pred]
new= np.array(new)
new